# Auto-migrated from pfts.json
name = "BorealEvergreen"
phenology = 1

[parameters]
phenological_type = 1
GDD0_full_leaf_out = -99.9
Emax = 4.5
root_fraction_top_soil = 0.83
tcurve = 0.8
dominance_factor = 3
sw_drop = -99.9
kk = 0.5
allocfact = 1.2
t0 = 0
max_min_canopy_conductance = 0.5
sapwood_respiration = 1
respfact = 4
grass = false
GDD5_full_leaf_out = -99.9
optratioa = 0.8
c4 = false
threshold = 0.33
leaf_longevity = 24
sw_appear = -99.9

