# Auto-migrated from pfts.json
name = "C3C4WoodyDesert"
phenology = 1

[parameters]
phenological_type = 1
GDD0_full_leaf_out = -99.9
Emax = 1
root_fraction_top_soil = 0.53
tcurve = 1
dominance_factor = 7
sw_drop = -99.9
kk = 0.3
allocfact = 1
t0 = 5
max_min_canopy_conductance = 0.1
sapwood_respiration = 1
respfact = 1.4
grass = false
GDD5_full_leaf_out = -99.9
optratioa = 0.7
c4 = true
threshold = 0.33
leaf_longevity = 12
sw_appear = -99.9

