# Auto-migrated from pfts.json
name = "CoolConifer"
phenology = 1

[parameters]
phenological_type = 1
GDD0_full_leaf_out = -99.9
Emax = 4.8
root_fraction_top_soil = 0.52
tcurve = 0.9
dominance_factor = 3
sw_drop = -99.9
kk = 0.5
allocfact = 1.2
t0 = 3
max_min_canopy_conductance = 0.2
sapwood_respiration = 1
respfact = 0.8
grass = false
GDD5_full_leaf_out = -99.9
optratioa = 0.9
c4 = false
threshold = 0.4
leaf_longevity = 30
sw_appear = -99.9

