# Auto-migrated from pfts.json
name = "TropicalEvergreen"
phenology = 1

[parameters]
phenological_type = 1
GDD0_full_leaf_out = -99.9
Emax = 10
root_fraction_top_soil = 0.69
tcurve = 1
dominance_factor = 1
sw_drop = -99.9
kk = 0.7
allocfact = 1
t0 = 10
max_min_canopy_conductance = 0.5
sapwood_respiration = 1
respfact = 0.8
grass = false
GDD5_full_leaf_out = -99.9
optratioa = 0.95
c4 = false
threshold = 0.25
leaf_longevity = 18
sw_appear = -99.9

