name: clouds
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.16
  - anaconda-client=1.12.3
  - anaconda-project=0.11.1
  - annotated-types=0.6.0
  - anyio=3.7.1
  - archspec=0.2.3
  - astroid=3.1.0
  - asttokens=2.4.1
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - black=24.3.0
  - boa=0.17.0
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfgv=3.3.1
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - codespell=2.2.6
  - colorama=0.4.6
  - conda=24.3.0
  - conda-build=24.3.0
  - conda-index=0.4.0
  - conda-libmamba-solver=24.1.0
  - conda-pack=0.7.1
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distlib=0.3.8
  - distro=1.9.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.3
  - flake8=7.0.0
  - flake8-black=0.3.6
  - fmt=10.2.1
  - freetype=2.12.1
  - icu=73.2
  - identify=2.5.35
  - idna=3.6
  - imagesize=1.4.1
  - importlib-metadata=4.13.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - ipdb=0.13.13
  - ipython=8.22.2
  - isort=5.13.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - json5=0.9.24
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.2
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libarchive=3.7.2
  - libcurl=8.7.1
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblief=0.14.1
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libpng=1.6.43
  - libsolv=0.7.28
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - livereload=2.6.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.2
  - menuinst=2.0.2
  - more-itertools=10.2.0
  - mypy=1.9.0
  - mypy_extensions=1.0.0
  - nbformat=5.10.4
  - ncurses=6.4.20240210
  - nodeenv=1.8.0
  - openjpeg=2.5.2
  - openssl=3.2.1
  - packaging=24.0
  - parso=0.8.4
  - patch=2.7.6
  - patchelf=0.17.2
  - pathspec=0.12.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pkginfo=1.10.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - pre-commit=3.7.0
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.14.1
  - pybind11-abi=4
  - pycodestyle=2.11.1
  - pycosat=0.6.6
  - pycparser=2.22
  - pydantic-core=2.16.3
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygments=2.17.2
  - pylint=3.1.0
  - pysocks=1.7.1
  - pytest=8.1.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-libarchive-c=5.1
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytz=2024.1
  - pyyaml=6.0.1
  - readline=8.2
  - referencing=0.34.0
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - rich=13.7.1
  - ripgrep=14.1.0
  - rope=1.13.0
  - rpds-py=0.18.0
  - rstcheck=6.2.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - ruamel_yaml=0.15.80
  - setuptools=69.2.0
  - shellingham=1.5.4
  - six=1.16.0
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sphinx=7.2.6
  - sphinx-autobuild=2024.2.4
  - sphinxcontrib-applehelp=1.0.8
  - sphinxcontrib-devhelp=1.0.6
  - sphinxcontrib-htmlhelp=2.0.5
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.7
  - sphinxcontrib-serializinghtml=1.1.10
  - stack_data=0.6.2
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.4
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - truststore=0.8.0
  - typer=0.12.1
  - typer-slim=0.12.1
  - typer-slim-standard=0.12.1
  - types-setuptools=69.0.0.0
  - types-toml=0.10.8.20240310
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ukkonen=1.0.1
  - urllib3=2.2.1
  - virtualenv=20.25.1
  - watchgod=0.8.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zipp=3.17.0
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - copier==7.2.0
      - docutils==0.19
      - dunamai==1.19.2
      - flake8-pyproject==1.2.3
      - fsspec==2024.3.1
      - funcy==2.0
      - jinja2-ansible-filters==1.3.2
      - mistune==2.0.5
      - plumbum==1.8.2
      - prompt-toolkit==3.0.36
      - pydantic==1.10.15
      - pyyaml-include==2.0
      - questionary==2.0.1
      - rstcheck-core==1.0.3
      - sphinx-mdinclude==0.5.3
      - types-docutils==0.19.1.9
