name: biome4
channels:
  - defaults
  - conda-forge
dependencies:
  - annotated-types=0.6.0
  - archspec=0.2.3
  - astroid=3.2.2
  - basemap=1.4.1
  - basemap-data=1.3.2
  - basemap-data-hires=1.3.2
  - black=24.4.2
  - blas=2.122
  - blas-devel=3.9.0
  - blosc=1.21.6
  - boltons=23.0.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.32.2
  - ca-certificates=2024.7.2
  - cartopy=0.22.0
  - cctools=986
  - cctools_osx-arm64=986
  - certifi=2024.7.4
  - cffi=1.16.0
  - cftime=1.6.2
  - charset-normalizer=2.0.4
  - clang=18.1.8
  - clang-18=18.1.8
  - clang_impl_osx-arm64=18.1.8
  - clang_osx-arm64=18.1.8
  - clangxx=18.1.8
  - click=8.1.7
  - colorama=0.4.6
  - compiler-rt=18.1.8
  - compiler-rt_osx-arm64=18.1.8
  - conda=24.5.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - contourpy=1.2.0
  - cycler=0.11.0
  - dill=0.3.8
  - distro=1.9.0
  - docutils=0.18.1
  - flake8=7.0.0
  - fmt=9.1.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - geos=3.12.1
  - gfortran=11.3.0
  - gfortran_impl_osx-arm64=13.2.0
  - gfortran_osx-arm64=13.2.0
  - gmp=6.2.1
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=75.1
  - idna=3.7
  - imageio=2.33.1
  - importlib-metadata=2.0.0
  - isl=0.25
  - isort=5.13.2
  - jsonpatch=1.33
  - jsonpointer=2.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.16
  - ld64=711
  - ld64_osx-arm64=711
  - lerc=4.0.0
  - libaec=1.1.3
  - libarchive=3.6.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libcurl=8.8.0
  - libcxx=18.1.8
  - libdeflate=1.20
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran-devel_osx-arm64=13.2.0
  - libgfortran5=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm18=18.1.8
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libopenlibm4=0.8.1
  - libpng=1.6.43
  - libsolv=0.7.30
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - llvm-tools=18.1.8
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown-it-py=2.2.0
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mccabe=0.7.0
  - mdurl=0.1.0
  - menuinst=2.1.1
  - meson=1.3.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mypy=1.10.0
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - netcdf-fortran=4.6.1
  - netcdf4=1.7.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numba=0.60.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.27
  - openjpeg=2.5.2
  - openlibm=0.8.1
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - pathspec=0.10.3
  - pillow=10.0.1
  - pip=24.0
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - proj=9.3.1
  - psutil=5.9.0
  - pthread-stubs=0.3
  - pybind11-abi=5
  - pycodestyle=2.11.1
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygments=2.15.1
  - pylint=3.2.2
  - pyparsing=3.0.9
  - pyproj=3.6.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2024.1
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.2
  - rich=13.7.1
  - rstcheck=6.2.4
  - rstcheck-core=1.2.1
  - ruamel.yaml=0.17.21
  - setuptools=69.5.1
  - shapely=2.0.4
  - shellingham=1.5.0
  - sigtool=0.1.3
  - six=1.16.0
  - snappy=1.2.1
  - snowballstemmer=2.2.0
  - sqlite=3.46.0
  - tapi=1100.0.11
  - tbb=2021.8.0
  - tk=8.6.13
  - tomlkit=0.11.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - truststore=0.8.0
  - typer=0.9.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wheel=0.43.0
  - xarray=2023.6.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zipp=3.17.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
