name: cloud-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.16
  - alsa-lib=1.2.11
  - anaconda-client=1.12.3
  - anaconda-project=0.11.1
  - annotated-types=0.6.0
  - anyio=3.7.1
  - aom=3.8.2
  - archspec=0.2.3
  - astroid=3.1.0
  - asttokens=2.4.1
  - attr=2.5.1
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - black=24.4.0
  - boa=0.17.0
  - boltons=24.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfgv=3.3.1
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - codespell=2.2.6
  - colorama=0.4.6
  - conda=24.3.0
  - conda-build=24.3.0
  - conda-index=0.4.0
  - conda-libmamba-solver=24.1.0
  - conda-pack=0.7.1
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.2.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - dbus=1.13.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distlib=0.3.8
  - distro=1.9.0
  - double-conversion=3.3.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=6.1.1
  - filelock=3.13.4
  - flake8=7.0.0
  - flake8-black=0.3.6
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.80.0
  - glib-tools=2.80.0
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.14.0
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - icu=73.2
  - identify=2.5.35
  - idna=3.7
  - imagesize=1.4.1
  - imath=3.1.11
  - importlib-metadata=4.13.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - ipdb=0.13.13
  - ipython=8.22.2
  - isort=5.13.2
  - jasper=4.2.3
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - json5=0.9.25
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.3
  - libarchive=3.7.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.3
  - libclang13=18.1.3
  - libcups=2.3.3
  - libcurl=8.7.1
  - libdeflate=1.20
  - libdrm=2.4.120
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libglu=9.0.0
  - libgomp=13.2.0
  - libgpg-error=1.48
  - libhwloc=2.10.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblief=0.14.1
  - libllvm18=18.1.3
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.4
  - libopenblas=0.3.27
  - libopencv=4.9.0
  - libopenvino=2024.0.0
  - libopenvino-auto-batch-plugin=2024.0.0
  - libopenvino-auto-plugin=2024.0.0
  - libopenvino-hetero-plugin=2024.0.0
  - libopenvino-intel-cpu-plugin=2024.0.0
  - libopenvino-intel-gpu-plugin=2024.0.0
  - libopenvino-ir-frontend=2024.0.0
  - libopenvino-onnx-frontend=2024.0.0
  - libopenvino-paddle-frontend=2024.0.0
  - libopenvino-pytorch-frontend=2024.0.0
  - libopenvino-tensorflow-frontend=2024.0.0
  - libopenvino-tensorflow-lite-frontend=2024.0.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.25.3
  - libsndfile=1.2.2
  - libsolv=0.7.28
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.21.0
  - libvorbis=1.3.7
  - libvpx=1.14.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.6
  - libzlib=1.2.13
  - livereload=2.6.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - menuinst=2.0.2
  - more-itertools=10.2.0
  - mpg123=1.32.6
  - munkres=1.1.4
  - mypy=1.9.0
  - mypy_extensions=1.0.0
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbformat=5.10.4
  - ncurses=6.4.20240210
  - nettle=3.9.1
  - nodeenv=1.8.0
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - opencv=4.9.0
  - openexr=3.2.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.2.1
  - p11-kit=0.24.1
  - packaging=24.0
  - pandas=2.2.2
  - parso=0.8.4
  - patch=2.7.6
  - patchelf=0.17.2
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - pkginfo=1.10.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - pre-commit=3.7.0
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulseaudio-client=17.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-lief=0.14.1
  - py-opencv=4.9.0
  - pybind11-abi=4
  - pycodestyle=2.11.1
  - pycosat=0.6.6
  - pycparser=2.22
  - pydantic-core=2.18.1
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygments=2.17.2
  - pylint=3.1.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pytest=8.1.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-libarchive-c=5.1
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytz=2024.1
  - pyyaml=6.0.1
  - qt6-main=6.6.3
  - readline=8.2
  - referencing=0.34.0
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - rich=13.7.1
  - ripgrep=14.1.0
  - rope=1.13.0
  - rpds-py=0.18.0
  - rstcheck=6.2.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - ruamel_yaml=0.15.80
  - scipy=1.13.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=69.5.1
  - shellingham=1.5.4
  - six=1.16.0
  - snappy=1.2.0
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sphinx=7.3.5
  - sphinx-autobuild=2024.4.16
  - sphinxcontrib-applehelp=1.0.8
  - sphinxcontrib-devhelp=1.0.6
  - sphinxcontrib-htmlhelp=2.0.5
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.7
  - sphinxcontrib-serializinghtml=1.1.10
  - stack_data=0.6.2
  - starlette=0.37.2
  - statsmodels=0.14.1
  - svt-av1=2.0.0
  - tbb=2021.12.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.4
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - truststore=0.8.0
  - typer=0.12.3
  - typer-slim=0.12.3
  - typer-slim-standard=0.12.3
  - types-setuptools=69.5.0.20240415
  - types-toml=0.10.8.20240310
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ukkonen=1.0.1
  - ultralytics=8.2.1
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - uvicorn=0.29.0
  - virtualenv=20.25.3
  - watchfiles=0.21.0
  - watchgod=0.8.2
  - wcwidth=0.2.13
  - websockets=12.0
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.41
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - copier==7.2.0
      - docutils==0.19
      - dunamai==1.20.0
      - flake8-pyproject==1.2.3
      - fsspec==2024.3.1
      - funcy==2.0
      - jinja2-ansible-filters==1.3.2
      - mistune==2.0.5
      - mpmath==1.3.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - plumbum==1.8.2
      - prompt-toolkit==3.0.36
      - pydantic==1.10.15
      - pyyaml-include==2.0.1
      - questionary==2.0.1
      - rstcheck-core==1.0.3
      - sphinx-mdinclude==0.5.3
      - sympy==1.12
      - thop==0.1.1-2209072238
      - torch==2.2.2
      - torchvision==0.17.2
      - triton==2.2.0
      - types-docutils==0.19.1.9
